### ISSUE TITLE
dotCover started even if not requested to be started in the build configuration

### ISSUE THREAD

**Issue by NikolayPianikov** [JetBrains/teamcity-dotnet-plugin#130] opened 2018-06-26 15:35 UTC
TC 2017.2.4 (build 51228)

1. Create build step "dotnet test" with dotCover enabled
2. Clone "dotnet test" step and change to "dotnet build" on the clone, reorder clone to be the first step
3. Open "dotnet build" step editor - there is no dotCover selected (and even no possibility to select it)
4. When you run the configuration, the first step log shows that dotCover is started for build:

```
Step 1/2: Build (.NET CLI (dotnet))
(running for 3m:56s)
[09:46:26]dotnet.exe build @C:\BuildAgent\temp\agentTmp\f37328e12a214f5cb4a8152dabcb4c23.rsp
[09:46:26]build
(running for 3m:56s)
[09:46:26]Starting: C:\BuildAgent\tools\JetBrains.dotCover.CommandLineTools.bundled\dotCover.exe cover C:\BuildAgent\temp\buildTmp\34fd495502774a35b88ea2af6e049f57.dotCover /ReturnTargetExitCode /NoCheckForUpdates /AnalyzeTargetArguments=false
```

Originally from: https://teamcity-support.jetbrains.com/hc/en-us/community/posts/360000020540-Dotnet-CLI-dotCover-started-even-if-not-requested-to-be-started-in-the-build-configuration

**Comment by mchechulnikov** [comment] 2023-11-07 15:50
I can not reproduce the issue on the TeamCity 2023.11 version. It seems that the issue is quite outdated, so I'm closing the issue for now.

**Closed by mchechulnikov** 2023-11-07 15:50 UTC
Labels: bug
