### ISSUE TITLE
NuGet restore: Unable to load the service index for source 

### ISSUE THREAD

**Issue by capiono** [JetBrains/teamcity-dotnet-plugin#25] opened 2016-11-06 09:37 UTC
While running the dotnet restore step I get the error below:

> [Step 1/2] Starting: "C:\Program Files\dotnet\dotnet.exe" restore
> [Step 1/2] in directory: C:\TeamCity\buildAgent\work\279c3e8f3593f219
> [Step 1/2] log  : Restoring packages for C:\TeamCity\buildAgent\work\279c3e8f3593f219\src\App\project.json...
> [Step 1/2] log  : Restoring packages for C:\TeamCity\buildAgent\work\279c3e8f3593f219\src\App\project.json...
> [Step 1/2] error: Unable to load the service index for source https://api.nuget.org/v3/index.json.
> [Step 1/2] error:   An error occurred while sending the request.
> [Step 1/2] error:   A connection with the server could not be established

I have enabled and installed Nuget Server/tool.

How do I fix this?

**Comment by dtretyakov** [comment] 2016-11-07 15:33
@oerhahon, it may be caused by invalid connection settings on your build agent machine.

Could you try to run `dotnet restore` for this project on build agent machine from the command line?

If it also does not work and you need to use proxy server you can try to specify [proxy settings](https://docs.nuget.org/ndocs/schema/nuget.config-file#config-section) and try again.

**Comment by dtretyakov** [comment] 2016-11-15 18:39
@capiono, does it properly work now?

**Comment by seriouz** [comment] 2016-12-23 18:59
I have the some problem and restoring from console is working.

**Comment by dtretyakov** [comment] 2016-12-26 15:39
@seriouz, please describe in which infrastructure `dotnet restore` fails?

**Comment by capiono** [comment] 2017-01-11 15:03
Yes, console restore works, but doesn't work from TeamCity.

**Comment by dtretyakov** [comment] 2017-01-12 17:12
@capiono, what version of .net core cli do you use on this machine?

**Comment by capiono** [comment] 2017-01-12 19:55
1.1.0

Get Outlook for Android<https://aka.ms/ghei36>



On Thu, Jan 12, 2017 at 12:12 PM -0500, "Dmitry Tretyakov" <notifications@github.com<mailto:notifications@github.com>> wrote:


@capiono<https://github.com/capiono>, what version of .net core cli do you use on this machine?

**Comment by GDBSD** [comment] 2017-01-16 15:59
I have two solutions with identical project.json files. I am referencing "Moq": "4.6.38-alpha" from MyGet. Here's my NuGet.Config entry: 
<add key="MyGet1" value="https://www.myget.org/F/aspnet-contrib/api/v3/index.json" />

In Solution A this works just fine. However in Solution B I get the following exception:
Unable to load the service index for source https://api.nuget.org/v3/index.json.

It's a puzzle to me how two solutions with identical project.json files would behave this way.

**Comment by dtretyakov** [comment] 2017-01-18 10:57
@GDBSD, could you please try to run `dotnet restore` and `dotnet --version` from the command line in the solution A and solution B directory?

**Comment by dtretyakov** [comment] 2017-03-21 13:50
Closing due to release of stable .net core cli build.

**Comment by capiono** [comment] 2017-05-03 09:40
This is still an issue. 
I can run restore from command line, Team City is still producing the same error. I have converted to VS 2017 Project, that didn't change anything. 

dotnet --version: 1.0.3
nugget version 3.5.0

**Comment by dtretyakov** [comment] 2017-05-03 20:51
@capiono, did you tried to execute `dotnet restore` under the same user account which was used to run TeamCity build agent?

Could you add additional parameter `-v d` in the `dotnet restore` build step and share output?

If you need to use proxy server please verify after the build completion that at the `Parameters` tab of this build in the `Environment variables` section exists mention of _proxy_ variable.

Also you can take a look at the related issues:
 https://github.com/NuGet/Home/search?q=Unable+to+load+the+service+index+for+source&type=Issues

**Comment by seriouz** [comment] 2017-05-04 17:27
I have solved the issue some time ago with the following:

Log into the docker image
```
sudo docker exec -i -t teamcity-server-instance /bin/bash
```

Create a config file for nuget:
```
nano /root/.nuget/NuGet/NuGet.Config
```

Set the content:
```
<configuration>
  <config>
    <add key="http_proxy" value="http://proxy-adress:3128" />
    <add key="https_proxy" value="http://proxy-adress:3128" />
  </config>
</configuration>
```

Save the config and let the build agent build/restore once more through the teamcity gui.

**Comment by capiono** [comment] 2017-05-05 23:43
I was able to recreate the error with the service user (Local System) in a command prompt:
running: 

`dotnet restore  -v d`

 produces this:

> C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error : Unable to load th
> e service index for source https://api.nuget.org/v3/index.json.\r [C:\TeamCity\b
> uildAgent\work\279c3e8f3593f219\Fwims.sln]
> C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error :   An error occurr
> ed while sending the request.\r [C:\TeamCity\buildAgent\work\279c3e8f3593f219\Fw
> ims.sln]
> C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error :   A connection wi
> th the server could not be established [C:\TeamCity\buildAgent\work\279c3e8f3593
> f219\Fwims.sln]

But when I run the command under my account or Run as Admin, it works fine.

**Closed** 2017-05-06 11:42 UTC
Labels: question
