### ISSUE TITLE
Problem with passing empty valued parameter from build configuration to rsp-file

### ISSUE THREAD

**Issue by partemyeva** [JetBrains/teamcity-dotnet-plugin#163] opened 2023-01-11 08:56 UTC
Good day,

We are in the process of upgrading from `2018.2.2 (build 61245)` to `2022.10.1 (build 116934)`. 

Build configuration in `v2018.2.2` used `.NET CLI (dotnet)` runner with `msbuild` command and set system parameter to empty value.

![image](https://user-images.githubusercontent.com/44258087/211761564-05a0ae9d-2e19-44d0-89aa-3a483890f358.png)

Migrated build configuration in `v2022.10.1` used `.NET` runner with `msbuild` command and set system parameter to empty value.

Empty valued parameter passing behavior now is differ: in `v2018.2.2` the parameter is passed with empty string value, in `v2022.10.1` the parameter is not passed at all.

Please see the attached rsp-files [rsp.zip](https://github.com/JetBrains/teamcity-dotnet-plugin/files/10390560/rsp.zip) from the similar build configurations. File `test_2018_2_2.rsp` contains `/p:SomeParameter=""`, but `test_2022_10_1.rsp` does not.

Thank you

**Comment by mchechulnikov** [comment] 2023-10-30 17:43
@partemyeva hello!

Could you please advise it the issue is still valid?
There were a number of issues with MSBuild properties passing to the `dotnet` driver in a number of particular versions of .NET SDK and runtime, however they all should be fixed, AFAIK

**Comment by mchechulnikov** [comment] 2023-11-06 10:32
Closing the issue for now. Please feel free to reopen it if you need help.

**Closed by mchechulnikov** 2023-11-06 10:32 UTC
